### ISSUE TITLE
Use .catch as an alias for .fail to support the official spec.

### ISSUE THREAD

**Issue by RangerMauve** [Medium/kew#42]
Hey, it seems that the Promise implementation that is coming with JavaScript is going to be using `.catch()` instead of `.fail()` for catching rejected promises. Do you think you could support this method in order to be more compatible with the spec?

**Comment by nicks** [comment]
sure, i think we would accept a patch for this.

**Comment by RangerMauve** [comment]
Cool, I'll put it on my TODO list

**Comment by RangerMauve** [comment]
A quick question first: 

Am I correct to assume that the constructor doesn't take a single function with `resolve` and `reject` as parameters like the [native](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise) implementation?

If so, then it might just end up being confusing if it has `.catch()` but isn't used the exact same way.

**Comment by nicks** [comment]
right.

**Comment by RangerMauve** [comment]
Yeah, in that case it might be better to just leave `.fail` as the only way to catch (other than `.then`)
